const { extractAll } = require('./src/services/extractCompanyFromText');

const tests = [
  { id: 'REGTEST001', desc: 'Shopify Expert (E-commerce)\nWe are looking for a Shopify Expert, preferably located in Central or South America, to join our team and support the management of our e-commerce operations.\n\nResponsibilities:\n* Sourcing and managing suppliers through Alibaba\n* Administering and updating Shopify stores', expected: null },
  { id: 'REGTEST002', desc: 'I need a skilled web developer to create a professional website for my bakery. The site should showcase our products, provide contact information, and offer a seamless user experience. The ideal candidate will have experience in web design and development, particularly with bakeries or similar businesses.', expected: null },
  { id: 'REGTEST003', desc: 'Grupo Noa International is looking for English-Azerbaijani experienced Interpreters.\n\nThe ideal candidate must be :\n1. Fluent in English and Azerbaijani \n2. Must know medical terminologies.', expected: 'Grupo Noa International' },
  { id: 'REGTEST004', desc: 'Update the user experience of an existing WordPress website hosted by Namecheap. The focus is on improving usability, navigation, and overall UX while working within the existing platform and hosting setup.', expected: null },
  { id: 'REGTEST005', desc: 'Pelonkey is a boutique experiential entertainment and creative production agency specializing in immersive corporate events, activations, entertainment-driven environments, and high-end guest experiences.\n\nWe are currently evolving our company from a traditional entertainment provider into a more elevated experiential creative agency and production house', expected: 'Pelonkey' },
  { id: 'REGTEST006', desc: 'NorthwoodsBitcoin Shopify Store Build Brief\nProject Overview\nBuild a clean, professional, trustworthy Shopify store for NorthwoodsBitcoin, a local Bitcoin-focused business. The brand emphasizes education, self-custody sovereignty, and practical Bitcoin tools.', expected: 'NorthwoodsBitcoin' },
  { id: 'REGTEST007', desc: 'We are a small Shopify theme studio behind Materia Themes. We create premium Shopify themes and currently have several demo stores/templates that need to be rebuilt using our newest theme version.\n\nThis is a simple but detail-focused task.', expected: 'Materia Themes' },
  { id: 'REGTEST008', desc: 'About the Company:\n\nWe are a private U.S.-based company operating across multiple departments that support legal, staffing, and client-service operations. Our teams collaborate in dynamic, fast-paced environments focused on innovation, integrity, and client success.', expected: null },
  { id: 'REGTEST009', desc: 'Join Young With Solutions as our next Recruiter!\n\nWe are looking for a driven Talent Acquisition Specialist to own the end-to-end hiring process for Young With Solutions.', expected: 'Young With Solutions' },
  { id: 'REGTEST010', desc: 'About LAMI Architects LAMI Architects is a boutique architecture and design studio with offices in Dubai and Tbilisi, delivering premium residential and hospitality projects across the UAE, KSA, Iraq, and the wider region.', expected: 'LAMI Architects' },
  { id: 'REGTEST011', desc: 'We are a digital marketing agency launching paid acquisition for a client Flutter mobile app. Create a GTM container for equippedproperty.com', expected: 'Equippedproperty' },
  { id: 'REGTEST012', desc: 'I had ChatGPT create me 2 webpages in HTML.\nI just plugged these in to my Kajabi website and below is what pages look like in Kajabi.\n\nhttps://www.brainathlete.club/shawn-ryan-show-memory-course\n\nMy current shopify website is www.brainathlete.com', expected: 'Brainathlete' },
  { id: 'REGTEST013', desc: 'We are trying to maximise our Google Page Speed Insights Score.\nOur site is a Woocommerce web store.\nWe are getting wildly variable scores on pagespeed insights:\nhttps://pagespeed.web.dev/analysis/https-interconnective-co-uk/bdspighi6h', expected: 'Interconnective' },
  { id: 'REGTEST014', desc: 'BongLine Prototype Engineer Needed\n\nI am looking for an experienced Product Design Engineer to help bring my consumer product idea to life.\n\nThe product is called BongLine\nIt is a fully circular breakaway poking tool dispenser.\n\nThank you.\nJoseph DeAngelis\nFounder | BongLine', expected: 'BongLine' },
  { id: 'REGTEST015', desc: 'We are currently looking for an experienced and highly skilled React Developer to join our development team for a large-scale enterprise web platform project.\n\nThis is not a simple landing page project. We are building a modern corporate digital platform.\n\nThe project inspiration and quality standard are similar to:\nhttps://www.intelliswift.com', expected: null },
  { id: 'REGTEST016', desc: 'We are seeking a highly experienced Senior Mobile Developer with strong expertise across Flutter, iOS (Swift), and Kotlin (Android) to resolve a critical and complex issue in a production level mobile application.\n\nThe app is experiencing inconsistent UI rendering.', expected: null },
  { id: 'REGTEST017', desc: 'NO AGENCIES. INDIVIDUAL APPLICANTS ONLY.\n\nAbout the Role\nWe are looking for a Marketing Associate to support the execution of our digital marketing programs.\n\nSecurity/Compliance:\n- All Metadata contractors, advisors, and consultants with access to internal company systems or databases must meet the following security and compliance requirements:\n- Read and accept company policies, including the Code of Conduct.', expected: 'Metadata' },
  { id: 'REGTEST018', desc: 'I need to hire someone to build a software for my company to use internally to track and compensate people to put advertisements on peoples front doors.\n\nBasically like DoorDash but for hanging advertisements on residential homes.\n\nThe website that I am duplicating is getcanvasser.com (when it works).', expected: null },
  { id: 'REGTEST019', desc: 'OVERVIEW\n\nWe are looking for someone experienced with WordPress to look at an existing site (thedragontrip.com) that has become slow.\n\nIt has not had much attention for the past year.', expected: 'DragonTrip' },
  { id: 'REGTEST020', desc: 'We are MegaJetters, LLC, a Detroit-based emergency plumbing and sewer company with a professionally designed website (megajetters.com) that is currently under-performing on lead generation. We need a skilled, results-driven digital marketing expert to take full ownership of the site.', expected: 'MegaJetters, LLC' },
  { id: 'REGTEST021', desc: 'We are a neurotech startup developing treatments for major neurological conditions, based on VR-based brain stimulation. We are preparing a clinical study scheduled to launch later this year and need a senior VR/Unity development partner.', expected: null },
  { id: 'REGTEST022', desc: 'We are an established multi-store ecommerce retail company looking for a highly skilled Shopify expert to help improve conversion rate, website performance, and overall user experience across our Shopify stores.\n\nThis is NOT just a basic Shopify VA role.', expected: null },
  { id: 'REGTEST023', desc: 'We run a free online image vectorization tool that converts PNG and JPG images to SVG files using AI. The site receives 1,000+ organic visitors per day.\n\nWe need an experienced Python/Flask developer to build a Google Drive integration.', expected: null },
  { id: 'REGTEST024', desc: 'We are seeking a skilled freelancer to design a visually appealing and functional website using Wix. The ideal candidate will have experience in creating engaging web pages that align with our brand identity.', expected: null },
  { id: 'REGTEST025', desc: 'Part-time to start. Weekly tasks to update and expand existing WP/Elementor website Locl.ai. You will work with Success and executive team directly. Design skills helpful.', expected: 'Locl.ai' },
  { id: 'REGTEST026', desc: 'We are looking for an experienced Operations Manager to oversee and streamline our day-to-day business operations across supply chain, fulfillment, and internal processes.\n\nThis role is ideal for someone who is highly organized, proactive, and comfortable managing multiple moving parts.', expected: null },
  { id: 'REGTEST027', desc: 'We are a neurotech startup developing non-invasive sensory stimulation treatments for major neurological conditions. We are preparing a clinical study on patients with a neurodegenerative condition, scheduled to launch later this year.', expected: null },
  { id: 'REGTEST028', desc: 'Hey,\nI am looking for a reliable full stack developer to work on a SaaS project and custom payment integration. Preferably someone experienced with React/Next.js, Node.js, APIs, databases.\nSaaS experience is a big plus.', expected: null },
  { id: 'REGTEST029', desc: 'Hi Ved, hope you doing well.\n\nI need help to set up Shopify design and have the website running for perfume decant business.\n\nPlease let me know when you can start the project.', expected: null },
  { id: 'REGTEST030', desc: 'We are seeking an experienced app developer to integrate Cloud AI and automation features into our mobile application. The ideal candidate will have a strong background in mobile app development and experience with Cloud AI technologies.', expected: null },
];

let pass = 0, fail = 0;
for (const t of tests) {
  const result = extractAll(t.desc);
  const actual = result.company;
  const ok = (actual === t.expected);
  if (!ok) fail++;
  else pass++;
  const marker = ok ? 'PASS' : 'FAIL';
  console.log('[' + marker + '] ' + t.id + ': expected="' + t.expected + '" got="' + actual + '"');
}
console.log('\n' + pass + '/' + tests.length + ' passed');
if (fail > 0) process.exit(1);