/**
 * Niche allow-list: phrase must contain at least one token (substring match).
 * Tokens are normalized to lowercase for matching.
 */
const NICHE_PHRASES = [
  'web',
  'frontend',
  'react',
  'next',
  'vue',
  'angular',
  'typescript',
  'javascript',
  'node',
  'api',
  'graphql',
  'ai',
  'llm',
  'rag',
  'agent',
  'gpt',
  'claude',
  'langchain',
  'langgraph',
  'mcp',
  'embedding',
  'vector',
  'test',
  'qa',
  'playwright',
  'cypress',
  'selenium',
  'automation',
  'e2e',
  'jest',
  'vitest',
  'devops',
  'kubernetes',
  'docker',
  'terraform',
  'ansible',
  'ci',
  'cd',
  'pipeline',
  'github actions',
  'azure devops',
  'aws',
  'tanstack',
  'axios',
  'supabase',
  'prisma',
  'serverless',
  'observability',
  'sre',
  'release',
  'deployment',
  'cicd',
  'github',
  'open source',
  'backend',
  'fullstack',
  'frontend',
  'software',
  'tool',
  'platform',
  'framework',
  'startup',
  'b2b',
  'machine learning',
  'ml',
  'deep learning',
  'ai coding',
  'copilot',
  'cloud computing',
  'cloud native',
  'database',
  'db',
  'sql',
  'nosql',
  'mongodb',
  'postgresql',
  'redis',
  'microservices',
  'microservice',
  'service mesh',
  'binaries',
  'compile',
  'runtime',
  'sdk',
  'ide',
  'vscode',
  'debugging',
  'debugger',
  'breakpoint',
  'logging',
  'monitoring',
  'alerting',
  'metrics',
  'grafana',
  'prometheus',
  'datadog',
  'CI/CD',
  'gitops',
  'argocd',
  'helm',
  'kaniko',
  'buildpack',
  'container',
  'containerization',
  'virtualization',
  'vagrant',
  'podman',
  'containerd',
  'image',
  'registry',
  'harbor',
  'ecr',
  'gcr',
  'acr',
  'load balancer',
  'ingress',
  'nginx',
  'traefik',
  'istio',
  'envoy',
  'api gateway',
  'service discovery',
  'consul',
  'etcd',
  'vault',
  'secrets manager',
  'aws secrets',
  'gcp secret',
  'secret management',
  'authentication',
  'authorization',
  'oauth',
  'saml',
  'ldap',
  'jwt',
  'token',
  'session',
  'mfa',
  'zero trust',
  'pen test',
  'penetration testing',
  'vulnerability',
  'cve',
  'security scan',
  'sca',
  'sast',
  'dast',
  'sbom',
  'supply chain',
  'license compliance',
  'cryptography',
  'encryption',
  'tls',
  'ssl',
  'certificate',
  'pki',
  'identity',
  'access management',
  'iam',
  'rbac',
  'abac',
  'policy as code',
  'open policy agent',
  'opa',
  'cel',
  'rego',
  'falco',
  'aqua security',
  'trivy',
  'snyk',
  'dependabot',
  'renovate',
  'technical debt',
  'refactor',
  'legacy',
  'migration',
  'modernization',
  'monolith',
  'architecture',
  'design pattern',
  'event driven',
  'event sourcing',
  'cqrs',
  'Saga',
  'circuit breaker',
  'bulkhead',
  'retry',
  'timeout',
  'backpressure',
  'idempotent',
  'eventual consistency',
  'cap theorem',
  'distributed',
  'consensus',
  'raft',
  'paxos',
  'leader election',
  'sharding',
  'replication',
  'failover',
  'ha',
  'dr',
  'backup',
  'restore',
  'disaster recovery',
  'bcp',
  'sla',
  'slo',
  'slm',
  'error budget',
  'on call',
  'incident response',
  'postmortem',
  'blameless',
  'runbook',
  'playbook',
  'observability',
  'distributed tracing',
  'tracing',
  'span',
  'trace id',
  'correlation id',
  'opentelemetry',
  'jaeger',
  'zipkin',
  'lightstep',
  ' honeycomb',
  'structured log',
  'log aggregation',
  'elk',
  'elasticsearch',
  'loki',
  'splunk',
  'sumologic',
  'papertrail',
  'cloudwatch',
  'stackdriver',
  'bugsnag',
  'sentry',
  'rollbar',
  'performance',
  'profiling',
  'flamegraph',
  'pprof',
  'async',
  'thread',
  'concurrency',
  'parallelism',
  'worker thread',
  'web worker',
  'cluster mode',
  'pm2',
  'forever',
  'systemd',
  'supervisor',
  'process manager',
  'health check',
  'liveness probe',
  'readiness probe',
  'startup probe',
  'graceful shutdown',
  'drain',
  'rolling update',
  'blue green',
  'canary',
  'feature flag',
  'launchdarkly',
  'unleash',
  'split',
  'optimizely',
  'ab test',
  'experimentation',
  'feature toggle',
  'tech lead',
  'engineering manager',
  'architect',
  'staff engineer',
  'principal engineer',
  'senior engineer',
  'code review',
  'pull request',
  'merge',
  'rebase',
  'squash',
  'cherry pick',
  'bisect',
  'blame',
  'hook',
  'precommit',
  'prepush',
  'lint',
  'prettier',
  'eslint',
  'ruff',
  'golangci',
  'shellcheck',
  'hadolint',
  'dockerfile',
  'multistage build',
  'layer cache',
  'buildkit',
  'buildah',
  'img',
  'kaniko',
  'distroless',
  'chaos engineering',
  'gremlin',
  'litmus',
  'chaos monkey',
  'toxiproxy',
  'failure injection',
  'game days',
  '冥想',
  'incident',
  'severity',
  'p1',
  'p2',
  'tier 1',
  'tier 2',
  'support',
  'l1',
  'l2',
  'l3',
  'ticketing',
  'jira',
  'linear',
  'asana',
  'monday',
  'notion',
  'confluence',
  'wiki',
  'knowledge base',
  'slack',
  'teams',
  'webhook',
  'chatbot',
  'bot',
  'automation',
  'n8n',
  'zapier',
  'make',
  'workflow',
  'integration',
  'webhook',
  'event driven',
  'serverless',
  'function',
  'lambda',
  'cloud function',
  'azure function',
  'gcf',
  'edge function',
  'netlify',
  'vercel',
  'cloudflare',
  'workers',
  'faas',
  'serverless framework',
  'serverless compose',
  'aws sam',
  'chalice',
  'zappa',
  'openfaas',
  'knative',
  'trigger',
  'cron',
  'schedule',
  'event',
  'message queue',
  'mq',
  'rabbitmq',
  'kafka',
  'activemq',
  'sqs',
  'sns',
  'pubsub',
  'google pubsub',
  'azure service bus',
  'eventhub',
  'solace',
  'nats',
  'zeromq',
  'stream processing',
  'flink',
  'spark',
  'storm',
  'samza',
  'kafka streams',
  'ksql',
  'ksqldb',
  'connector',
  'confluent',
  'schema registry',
  'avro',
  'protobuf',
  'thrift',
  'capnproto',
  'msgpack',
  'cbor',
  'json',
  'xml',
  'yaml',
  'toml',
  'hcl',
  'terraform',
  'pulumi',
  'cdk',
  'cloudformation',
  'arm template',
  'crossplane',
  'ansible',
  'chef',
  'puppet',
  'saltstack',
  'vagrant',
  'packer',
  'waypoint',
  'nomad',
  'consul',
  'vault',
  'nomad',
  'traefik',
  'envoy',
  'linkerd',
  'istio',
  'kuma',
  'cilium',
  'calico',
  'flannel',
  'weave',
  'canal',
  'kube-proxy',
  'kube-router',
  'cni',
  'cni plugin',
  'multus',
  'whereabouts',
  'ipam',
  'subnet',
  'vpc',
  'virtual private cloud',
  'subnetting',
  'cidr',
  'nat',
  'bastion',
  'jump host',
  'jumpbox',
  'dmz',
  'security group',
  'network policy',
  'firewall',
  'waf',
  'ddos',
  'rate limit',
  'throttling',
  'quota',
  'limit',
  'budget',
  'cost optimization',
  'reserved instance',
  'spot instance',
  'savings plan',
  'commitment',
  'finops',
  'cloud cost',
  'kubecost',
  'spotinst',
  'cast ai',
  'vent碎片',
  'dba',
  'database administration',
  'query optimization',
  'index',
  'partition',
  'shard',
  'replica set',
  'primary',
  'secondary',
  'read replica',
  'write ahead log',
  'wal',
  'checkpoint',
  'vacuum',
  'autovacuum',
  'analyze',
  'explain plan',
  'query plan',
  '慢查询',
  'connection pool',
  'pgbouncer',
  'haproxy',
  'maxscale',
  'mysql router',
  'mongodb memory',
  'wiredtiger',
  'rocksdb',
  'innodb',
  'myisam',
  'aurora',
  'dynamodb',
  'cassandra',
  'scylladb',
  'cockroachdb',
  'tidb',
  ' Yugabyte',
  'single store',
  'memcached',
  'aerospike',
  'leveldb',
  'badger',
  'lmdb',
  'timeseriesdb',
  'influxdb',
  'timescaledb',
  'questdb',
  'prometheus',
  'victoria metrics',
  'm3db',
  'glance',
  'grafana',
  'kibana',
  'dashboard',
  'visualization',
  'chart',
  'graph',
  'alert',
  'alertmanager',
  'alert rule',
  'silence',
  'inhibit',
  'routing',
  'amixr',
  'pagerduty',
  'victorops',
  'opsgenie',
  'squadcast',
  'statuspage',
  'c状态页',
  'status io',
  'healthchecks',
  'dead manns snack',
  'atma',
  'greenhouse',
  'clever cloud',
  'render',
  'railway',
  'fly.io',
  'dokku',
  'docker compose',
  'docker swarm',
  'kubernetes',
  'k8s',
  'minikube',
  'kind',
  'k3s',
  'k3d',
  'microk8s',
  'telepresence',
  'skaffold',
  'tilt',
  'garden',
  'devspace',
  'okteto',
  'stackery',
  'serverless',
  'knative',
  'openfaas',
  'fission',
  'nuclio',
  'ironfunctions',
  'aws lambda',
  'azure functions',
  'google cloud functions',
  'oracle functions',
  'alibaba function compute',
  ' Tencent cloud functions',
  'IBM functions',
  'auth0 functions',
  'netlify functions',
  'vercel serverless functions',
  'cloudflare workers',
  'fastly compute',
  'akamai edgeworkers',
  'limelight edge',
  'edge computing',
  'edge runtime',
  'webassembly',
  'wasm',
  'wasmtime',
  'wasmer',
  'wasi',
  'component model',
  'wandermere',
  'assemblyscript',
  'go',
  'golang',
  'rust',
  'rustlang',
  'c',
  'cpp',
  'cplusplus',
  'python',
  'ruby',
  'php',
  'perl',
  'java',
  'kotlin',
  'scala',
  'clojure',
  'haskell',
  'erlang',
  'elixir',
  'gleam',
  'ocaml',
  'fsharp',
  'functional programming',
  'reactive',
  'rx',
  'reactivex',
  'algebraic data type',
  'adt',
  'option',
  'result',
  'either',
  'monad',
  'functor',
  'applicative',
  'lens',
  'prism',
  'optics',
  'dependecy injection',
  'di',
  'ioc',
  'solid principles',
  'single responsibility',
  'open closed',
  'liskov substitution',
  'interface segregation',
  'dependency inversion',
  'dry',
  'kiss',
  'yagni',
  'boy scout rule',
  'wtf/min',
  'readable',
  'readability',
  'clean code',
  'code smell',
  'antipattern',
  'god object',
  'spaghetti code',
  'lasagna code',
  'ravioli code',
  'magic number',
  'hardcode',
  'constant',
  'enum',
  'typedef',
  'interface',
  'trait',
  'mixin',
  'abstract class',
  'method override',
  'overload',
  'polymorphism',
  'encapsulation',
  'abstraction',
  'inheritance',
  'composition',
  'aggregation',
  'association',
  'dependency',
  'coupling',
  'cohesion',
  'affinity',
  'banzai',
  'anti affinity',
  'node affinity',
  'pod affinity',
  'taint',
  'toleration',
  'drain',
  'cordon',
  'uncordon',
  'drain node',
  'kubectl',
  'kubectx',
  'kubens',
  'kubeon',
  'stern',
  'kail',
  'k9s',
  'kubespy',
  'kube-state-metrics',
  'metrics server',
  'vertical pod autoscaler',
  'vpa',
  'horizontal pod autoscaler',
  'hpa',
  'cluster autoscaler',
  'keda',
  'event driven autoscaling',
  'cron job autoscaler',
  'poddisruptionbudget',
  'pdb',
  'priorityclass',
  'resource request',
  'resource limit',
  'limitrange',
  'resourcequota',
  'QoS class',
  'best effort',
  'burstable',
  'guaranteed',
  'pod security context',
  'security context',
  'psp',
  'pod security policy',
  'networkpolicy',
  'rbac',
  'role',
  'rolebinding',
  'clusterrole',
  'clusterrolebinding',
  'service account',
  'token',
  'imagepullsecret',
  'secret',
  'configmap',
  'downward api',
  'projected volume',
  'emptydir',
  'hostpath',
  'persistentvolume',
  'persistentvolumeclaim',
  'pvc',
  'storageclass',
  'dynamic provisioning',
  'static provisioning',
  'local volume',
  'block storage',
  'file storage',
  'object storage',
  's3',
  'gcs',
  'azure blob',
  'aliyun oss',
  'cloudflare r2',
  'minio',
  'rook',
  'ceph',
  'longhorn',
  'openebs',
  'local path provisioner',
  'nfs',
  'efs',
  'fsx',
  'iscsi',
  'fc',
  'nvme-of',
  'RDMA',
  'infiniband',
  'serverless',
  'function as a service',
  'faas',
  'baas',
  'backend as a service',
  'serverless framework',
  'aws sam',
  'serverless application model',
  ' Chalice',
  'Zappa',
  'Pulumi',
  'AWS CDK',
  'cdk8s',
  'backstage',
  'goldilocks',
  'k8s-assert',
  'kube-hunter',
  'kube-bench',
  'kubesec',
  'trivy',
  'aqua',
  'snyk',
  'prisma',
  'sequelize',
  'typeorm',
  'knex',
  'query builder',
  'orm',
  'activerecord',
  'datamapper',
  'repository pattern',
  'unit of work',
  'lazy loading',
  'eager loading',
  'select n plus 1',
  'n plus 1 query',
  'eager vs lazy',
  'pagination',
  'cursor pagination',
  'offset pagination',
  'keyset pagination',
  'infinite scroll',
  'caching',
  'cache invalidation',
  'cache stampede',
  'thundering herd',
  'write through',
  'write behind',
  'write back',
  'read through',
  'cache aside',
  'LRU',
  'LFU',
  'FIFO',
  'ARC',
  'memcached',
  'redis',
  'aerospike',
  'caffeine',
  'ehcache',
  'jcache',
  'JCACHE',
  'spring cache',
  'cache manager',
  'distributed cache',
  'local cache',
  'cdn',
  'cloudfront',
  'cloudflare',
  'fastly',
  'akamai',
  'limelight',
  'cache-control',
  'etag',
  'last-modified',
  'surrogate key',
  'surrogate caching',
  'edge caching',
  'stale while revalidate',
  'stale-if-error',
  'content delivery network',
  'reverse proxy',
  'forward proxy',
  'proxy',
  'ngx_http_proxy_module',
  'traefik',
  'envoy',
  'nginx',
  'apache',
  'httpd',
  'caddy',
  'haproxy',
  'vulcand',
  'mole',
  'backend keepalive',
  'http keepalive',
  'tcp keepalive',
  'connection pooling',
  'multiplexing',
  'http2',
  'http3',
  'quic',
  'websocket',
  'long polling',
  'server sent events',
  'sse',
  'grpc',
  'grpc-web',
  'thrift',
  'avro',
  'protobuf',
  'msgpack',
  'firestore',
  'realtime database',
  'firebase',
  'supabase',
  'planetscale',
  'neon',
  'turso',
  'sqlite',
  'libsql',
  'drizzle',
  'prisma',
  'bookmarked'
];

/** Substrings; if any match (whole word or phrase), row is junk. */
const JUNK_SUBSTRINGS = [
  'amazon',
  'walmart',
  'near me',
  'crack',
  ' free ',
  'free download',
  'torrent',
  ' jobs',
  'jobs ',
  ' salary',
  'salary '
];

function normalizePhrase(s) {
  return String(s || '')
    .toLowerCase()
    .replace(/\s+/g, ' ')
    .trim();
}

function matchesNiche(normalized) {
  const padded = ` ${normalized} `;
  return NICHE_PHRASES.some((token) => {
    const t = token.toLowerCase();
    if (t.includes(' ')) return normalized.includes(t);
    const re = new RegExp(`(^|[^a-z0-9])${escapeRegExp(t)}([^a-z0-9]|$)`);
    return re.test(padded);
  });
}

function escapeRegExp(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

function isJunk(normalized) {
  if (!normalized || normalized.length < 3) return true;
  return JUNK_SUBSTRINGS.some((j) => normalized.includes(j));
}

module.exports = {
  NICHE_PHRASES,
  JUNK_SUBSTRINGS,
  normalizePhrase,
  matchesNiche,
  isJunk
};
